version: '3'

services:
  app:
        image: node
        volumes:
          - ./app:/app
        working_dir: /app
        command: sh -c 'npm install; npm run seed; npm start'
        ports:
          - "3000:8080"
