# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y%m/%d')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_type', models.CharField(choices=[('SS', 'Safe search'), ('LA', 'Labels'), ('WD', 'Web description')], max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Photo')),
            ],
        ),
    ]
