# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=20)),
            ],
        ),
    ]
